# Generated by Django 4.0.6 on 2022-08-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianchild',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
