# Generated by Django 4.0.6 on 2022-08-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('GUARDIAN', 'Guardian')], default='GUARDIAN', max_length=50),
        ),
    ]
