# Generated by Django 4.0.6 on 2022-08-06 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_avatar_user_avatar_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianchild',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.guardian'),
        ),
    ]
