# Generated by Django 4.0.6 on 2022-08-05 12:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.MyAccountManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('GUARDIAN', 'Guardian'), ('None', 'Other')], default='GUARDIAN', max_length=50),
        ),
    ]
