# Generated by Django 4.0.6 on 2022-08-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_guardianprofile_user_alter_schoolprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='alt_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('GUARDIAN', 'Guardian')], max_length=50, null=True),
        ),
    ]
