# Generated by Django 4.0.5 on 2022-08-02 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('debt_id', models.IntegerField()),
                ('school_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contend',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('debt_id', models.IntegerField()),
                ('guardian_id', models.IntegerField()),
                ('made_payment', models.BooleanField(default=False)),
                ('receipt', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
