# Generated by Django 4.0.5 on 2022-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='debt_id',
        ),
        migrations.RemoveField(
            model_name='contend',
            name='debt_id',
        ),
        migrations.AlterField(
            model_name='contend',
            name='receipt',
            field=models.CharField(max_length=400),
        ),
    ]
