# Generated by Django 4.0.6 on 2022-08-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_contend_created_at_alter_contend_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
    ]
